FROM node:26-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Important: Port must be dynamic as Vercel handles the port internally
ENV PORT=3000
CMD ["node", "dist/main"]